-- ============================================================
-- OLIST E-COMMERCE ANALYTICS
-- SQL / MySQL BUSINESS ANALYSIS
-- ============================================================
--
-- Objective:
-- Analyze Olist e-commerce order, payment, seller,
-- product and delivery performance data using SQL.
--
-- Tool:
-- MySQL Workbench 8.0
--
-- Key SQL concepts demonstrated:
-- SELECT, WHERE, GROUP BY, ORDER BY
-- Aggregate Functions
-- CASE WHEN
-- INNER JOIN / LEFT JOIN
-- CTEs
-- Subqueries
-- Window Functions
-- RANK()
-- LAG()
-- Date Conversion
-- DATEDIFF()
-- Primary Keys
-- Foreign Keys
-- Database Relationships
-- Data Quality & Reconciliation
--
-- ============================================================
-- 1. Overall Business KPIs
-- 2. Monthly Sales & Order Trend
-- 3. Payment Method Analysis
-- 4. Payment Method Contribution
-- 5. Customer Order Frequency
-- 6. Order Data Reconciliation
-- 7. Orders Without Items by Status
-- 8. Overall Order Status
-- 9. Delivery Performance
-- 10. Delivery Performance Classification
-- 11. Late Delivery Severity
-- 12. Seller Performance
-- 13. Top Seller Ranking
-- 14. Seller Freight Efficiency
-- 15. Product Performance
-- 16. Month-over-Month Sales Growth
-- 17. Top Seller Sales Contribution
-- 18. Final Business Performance Summary
-- 19. Final Delivery Data-Quality Check
-- 20. Final Delivery Performance
--
-- ============================================================
-- DATABASE DESIGN & RELATIONSHIP VALIDATION
-- ============================================================
--
-- 21. Primary Key Implementation
-- 22. Foreign Key Implementation
-- 23. Customer → Order Relationship Analysis
-- 24. Order → Order Item Relationship Analysis
-- 25. Order → Payment Relationship Analysis
-- 26. Order → Review Relationship Analysis
-- 27. Primary Key Uniqueness Validation
--
-- ============================================================
-- DATABASE RELATIONSHIPS
-- ============================================================
--
-- customers.customer_id
--        ↓
-- orders.customer_id
--
-- orders.order_id
--        ↓
-- order_items.order_id
--
-- orders.order_id
--        ↓
-- order_payments.order_id
--
-- orders.order_id
--        ↓
-- reviews.order_id
--
-- ============================================================
-- SQL PHASE COMPLETE
-- ============================================================
--
-- SQL analysis, database design, primary keys,
-- foreign keys and relationship validation completed.
--
-- Note:
-- The SQL reviews table contains only 279 loaded records.
-- Therefore, review-based SQL analysis is treated as a
-- relationship validation and not as the complete review analysis.
--
-- ============================================================
